services:
  mysql: 
    image: mariadb:10.7.8-focal
    volumes:
      - ".\\db:/var/lib/mysql"
      - ".\\dump-web.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
      - MARIADB_USER=user
      - MYSQL_PASSWORD=qwertyui
      - MARIADB_ROOT_PASSWORD=qwertyui 
      - MYSQL_DATABASE=web
    ports:
      - "127.0.0.1:3306:3306"
  frontend:
    build: frontend/.
    ports:
      - "8081:8080"
  backend:
    image: "trafex/php-nginx:latest"
    volumes:
      - ".\\backend:/var/www/html" 
    environment:
      - DBHOST=mysql
      - DBNAME=web
      - DBUSERNAME=root
      - DBPASSWORD=qwertyui
    ports:
      - "8080:8080"